# Generated by Django 3.1.8 on 2021-04-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210413_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='chiqarilgan_sanasi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
